package com.tom.immersivehudplugin.runtime;

public enum HudSignal {
    READY_GRACE,
    HOTBAR_INPUT,
    PLAYER_MOVING,
    PLAYER_WALKING,
    PLAYER_RUNNING,
    PLAYER_SPRINTING,
    PLAYER_MOUNTING,
    PLAYER_SWIMMING,
    PLAYER_FLYING,
    PLAYER_GLIDING,
    PLAYER_JUMPING,
    PLAYER_CROUCHING,
    PLAYER_CLIMBING,
    PLAYER_IN_FLUID,
    PLAYER_ON_GROUND,
    PLAYER_FALLING,
    PLAYER_SITTING,
    PLAYER_ROLLING,
    CHARGING_WEAPON,
    TARGET_ENTITY,
    INTERACTABLE_BLOCK,
    CONSUMABLE_USE,
    HOLDING_MELEE_WEAPON,
    HOLDING_RANGED_WEAPON
}