package com.tom.immersivehudplugin.runtime;

public enum HudSignal {
    READY_GRACE,
    HOTBAR_INPUT,
    PLAYER_MOVING,
    PLAYER_WALKING,
    PLAYER_RUNNING,
    PLAYER_SPRINTING,
    PLAYER_MOUNTING,
    PLAYER_SWIMMING,
    CHARGING_WEAPON,
    TARGET_ENTITY,
    INTERACTABLE_BLOCK,
    CONSUMABLE_USE,
    HOLDING_MELEE_WEAPON,
    HOLDING_RANGED_WEAPON
}